### ISSUE TITLE
--extract/--import not working as expected with title databases

### ISSUE THREAD

**Issue by ihaveamac** [wwylele/save3ds#1]
Using the options to extract and import don't seem to work with the same files as when mounting the file.
```
$ save3ds_fuse -b ~/.3ds/boot9.bin -m movable.sed --sd ./ --db sdtitle -i stuff 
Database file end fixup: 0x80
Clearing the original contents...
Importing new contents...
"stuff/000400000ff3ff00"
Finished
```
```
$ save3ds_fuse -b ~/.3ds/boot9.bin -m movable.sed --sd ./ --db sdtitle -x out
Database file end fixup: 0x80
Extracting...
-000400000ff3ff00
Finished
```
Upon mounting:
```
$ save3ds_fuse -b ~/.3ds/boot9.bin -m movable.sed --sd ./ --db sdtitle out
Database file end fixup: 0x80
Initialized
```
```
$ ls out
0004000000068100 000400000016de00 00040000001deb00 ...
```

**Comment by wwylele** [comment]
Could you test if https://github.com/wwylele/save3ds/commit/c11696077543d1c5797313e4e79f3fcbfe5afba5 fixed this?

**Comment by ihaveamac** [comment]
Yes, it looks like extract and import work on the same files as a mount now.

**Comment by wwylele** [comment]
btw please delete and backup from old version all the files you tested with the faulty extract/import. The wrong behaviour has caused data inconsistency. I am closing this as it is fixed.
