### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by alexisbietti** [wwylele/save3ds#2]
Hello, this is the first time I'm trying to build this project, so I may be missing a prerequisite or something.

alexis-2:save3ds alexis$ git log -n 1
commit a9bd1468751200ccd2d5285dd91482847d6a22ed (HEAD -> master, origin/master, origin/HEAD)
Author: Weiyi Wang <wwylele@gmail.com>
Date:   Sun Jun 23 16:14:02 2019 -0400

    disa: remove unnecessary test from template

alexis-2:save3ds alexis$ RUST_BACKTRACE=1 cargo build -v
       Fresh unicode-xid v0.1.0
       Fresh byte-tools v0.3.1
       Fresh pkg-config v0.3.15
       Fresh subtle v1.0.0
       Fresh opaque-debug v0.2.3
       Fresh cfg-if v0.1.9
       Fresh scopeguard v0.3.3
       Fresh fake-simd v0.1.2
       Fresh unicode-width v0.1.5
       Fresh thread-scoped v1.0.2
       Fresh block-padding v0.1.4
       Fresh getopts v0.2.19
       Fresh typenum v1.10.0
       Fresh proc-macro2 v0.4.30
       Fresh byteorder v1.3.2
       Fresh libc v0.2.60
       Fresh log v0.4.8
   Compiling fuse v0.3.1
       Fresh generic-array v0.12.3
     Running `/Users/alexis/Workspace/save3ds/target/debug/build/fuse-98fef41fa0de39c2/build-script-build`
       Fresh quote v0.6.13
       Fresh hashbrown v0.1.8
       Fresh time v0.1.42
       Fresh log v0.3.9
       Fresh block-cipher-trait v0.6.2
   Compiling dbl v0.2.1
     Running `rustc --crate-name dbl /Users/alexis/.cargo/registry/src/github.com-1ecc6299db9ec823/dbl-0.2.1/src/lib.rs --color always --crate-type lib --emit=dep-info,metadata,link -C debuginfo=2 -C metadata=f2780fe2b96f8f44 -C extra-filename=-f2780fe2b96f8f44 --out-dir /Users/alexis/Workspace/save3ds/target/debug/deps -L dependency=/Users/alexis/Workspace/save3ds/target/debug/deps --extern generic_array=/Users/alexis/Workspace/save3ds/target/debug/deps/libgeneric_array-d894cda1b29f4d4d.rlib --cap-lints allow`
error: failed to run custom build command for `fuse v0.3.1`

Caused by:
  process didn't exit successfully: `/Users/alexis/Workspace/save3ds/target/debug/build/fuse-98fef41fa0de39c2/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failure { command: "\"pkg-config\" \"--libs\" \"--cflags\" \"osxfuse\" \"osxfuse >= 2.6.0\"", output: Output { status: ExitStatus(ExitStatus(256)), stdout: "", stderr: "Package osxfuse was not found in the pkg-config search path.\nPerhaps you should add the directory containing `osxfuse.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'osxfuse\' found\nPackage osxfuse was not found in the pkg-config search path.\nPerhaps you should add the directory containing `osxfuse.pc\'\nto the PKG_CONFIG_PATH environment variable\nNo package \'osxfuse\' found\n" } }', src/libcore/result.rs:999:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::_print
             at src/libstd/sys_common/backtrace.rs:71
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/sys_common/backtrace.rs:59
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::try::do_call
             at src/libstd/panicking.rs:308
   7: <T as core::any::Any>::type_id
             at src/libcore/panicking.rs:85
   8: core::result::unwrap_failed
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/macros.rs:18
   9: core::result::Result<T,E>::unwrap
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libcore/result.rs:800
  10: build_script_build::main
             at ./build.rs:10
  11: std::rt::lang_start::{{closure}}
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  12: std::panicking::try::do_call
             at src/libstd/rt.rs:49
             at src/libstd/panicking.rs:293
  13: panic_unwind::dwarf::eh::read_encoded_pointer
             at src/libpanic_unwind/lib.rs:85
  14: <std::panicking::begin_panic::PanicPayload<A> as core::panic::BoxMeUp>::get
             at src/libstd/panicking.rs:272
             at src/libstd/panic.rs:394
             at src/libstd/rt.rs:48
  15: std::rt::lang_start
             at /rustc/a53f9df32fbb0b5f4382caaad8f1a46f36ea887c/src/libstd/rt.rs:64
  16: build_script_build::main

warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by wwylele** [comment]
Looks like some missing dependency for fuse. Could you try following the macOS section in https://github.com/zargony/rust-fuse readme? If it works, I will put these instructions in the readme here as well.

Alternatively if you couldn't get fuse work, you can build with `--no-default-features` to disable the fuse functionality and only use the import/export mode.

**Comment by wwylele** [comment]
Updated build instruction in 46715a8986aa712eb256173bea2d1a853a58d134

**Comment by alexisbietti** [comment]
I installed osxfuse and had to manually set the var PKG_CONFIG_PATH. Then it built fine! Thanks a lot

**Comment by alexisbietti** [comment]
NB: building with --no-default-feaure didn't remove the error.

**Comment by wwylele** [comment]
For `--no-default-feaure`, did you cd into the save3ds_fuse sub folder first? Otherwise because the main folder is a workspace you would get hit by https://github.com/rust-lang/cargo/issues/5015

**Comment by alexisbietti** [comment]
No I didn't! Sorry I don't know anything about rust & cargo ^^'
