### ISSUE TITLE
Import broken with 5660f8b

### ISSUE THREAD

**Issue by ihaveamac** [wwylele/save3ds#4]
Attempting to use `--import` seems to be broken (at least with sdtitle) starting with 5660f8b4f71da5d609f861bbc078a04b277b02c3. Extracting and mounting + writing works fine. Tested on macOS 10.15.1.

```
$ save3ds_fuse -b ~/.3ds/boot9.bin -m gm9/out/movable.sed --sd . --db sdtitle --import ~/Desktop/sdtitle
Database file end fixup: 0x80
Clearing the original contents...
Host IO error: Os { code: 9, kind: Other, message: "Bad file descriptor" }
Error: IO(Os { code: 9, kind: Other, message: "Bad file descriptor" })
```

**Comment by wwylele** [comment]
Should be fixed by https://github.com/wwylele/save3ds/commit/42a3030031ea2f5862c734ca137270cf74749da6

**Comment by ihaveamac** [comment]
Sorry for the late response, I tried it just now and it seems to work again.
