### ISSUE TITLE
Cannot extract Pokémon Sun cartridge savegame

### ISSUE THREAD

**Issue by Cu3PO42** [wwylele/save3ds#5]
First of all I would like to think you for making this, I had previously (two years ago or so) tried to get various other tools to decrypt saves, but was never quite able to make it work.

I am able to extract a save stored on my 3DS' SD card successfully. In particular, this works for my digital copy of Pokémon Sun. However, I am not able to get it working for a Pokémon Sun cartridge save. I understand the feature is marked experimental, so I'm hoping this might prove a useful bug report.

-----------------

I have a physical copy of the European version of Pokémon Sun, dumped using Godmode9. For completeness sake I also tested a dump by Uncart, but as expected they behave the same. Both the save and private header were also extracted using Godmode9.

Running
```
save3ds_fuse --boot9 ./boot9.bin --key ./0x2fKeyY.bin --readonly --extract \
    --cart ./0004000000164800_v00.sav \
    --priv ./0004000000164800_v00-priv.bin \
    --game ./0004000000164800_v00.3ds \
    ./mount
```
yields the following error message:
```
Size mismatch, caused by corrupted data
Error: SizeMismatch
```
Using some crude println debugging, I was able to trace this error to [line 179 of `wear_leveling.rs`](https://github.com/wwylele/save3ds/blob/master/libsave3ds/src/wear_leveling.rs#L179). The value for `len` that occurs is `0x100000`.

If, subsequently I change the check to allow this value of `len`, I then get the `SignatureMismatch` error in [line 96 of `wear_leveling.rs`](https://github.com/wwylele/save3ds/blob/master/libsave3ds/src/wear_leveling.rs#L96).

--------------

Unfortunately, the only other games I have on hand are Pokémon X and Pokémon OR, both of which are Card2. However, I saw [this commit](https://github.com/wwylele/save3ds/commit/72c2abe98ffaa956517a8127251d41bf4060846e) from yesterday, so I figured I would try it anyway. The only other way that the setup is different is that the saves I'm using are extracted using Powersaves (apparently Godmode9 does not yet support dumping Card2 save data?). I did, however strip their 0x9C large header, so it should be the raw save file.

And, in fact, both of these are working correctly.

---------------------

My setup is Rust 1.38 on macOS 10.13, however I would hope that this is not the cause of the issue.

For completeness' sake, I am also attaching the MD5's of boot9 and 0x2F KeyY, however I'm quite confident they are correct.

File | MD5
---|---
`boot9.bin` | `d8675e80e5dd3a9afaaf885d79b14e9c`
`0x2fKeyY.bin` | `48c1fef905d9a051bf752a71cca73e90`

**Comment by wwylele** [comment]
Looks like a new chip type that I haven't encountered before, so definitely my oversight here. Could you upload 0004000000164800_v00.sav?

**Comment by Cu3PO42** [comment]
I'm happy to share it with you, but would rather not make it entirely public. I will send you an email to the address specified in your profile.

I'd be glad if I can help in tracking this down :)

**Comment by wwylele** [comment]
Could you try this branch? https://github.com/wwylele/save3ds/tree/large-card1

**Comment by Cu3PO42** [comment]
I did try it and it seemed to work perfectly! I also tried a different save, wrote it to the cart, dumped it and it seems fine as well. Thank you so much for fixing it that swiftly!

I'm almost certain you're aware of this, but just in case, I did get the following warning during compilation:
```
warning: unreachable statement
   --> libsave3ds/src/wear_leveling.rs:235:17
    |
235 |                 return Err(Error::InvalidValue);
    |                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: `#[warn(unreachable_code)]` on by default
```

Do let me know if there's any further changes you need someone to test on this game.

**Comment by wwylele** [comment]
Thanks for the testing! Right now it isn't complete as I skipped a CRC check that I couldn't figure out. I probably need more help from you soon.

**Comment by wwylele** [comment]
I pushed the change (with some more modification) to the master branch https://github.com/wwylele/save3ds/commit/92756eede916401be60625ff134561ee2bf5c1ce. Please test it and feel free to close this if there is no problem.

**Comment by Cu3PO42** [comment]
As far as I can tell, that build also works correctly. Thank you again for the quick fix! 

Now I just need to figure out what commands to send to Powersaves... though I suppose that will prove much more painful to me.
